import Head from 'next/head';
// import { useState } from 'react';

export default function Record() {
  const now = new Date().toISOString().split('T')[0];

  const handleSubmit = (e: React.SyntheticEvent) => {
    // stop page reload
    e.preventDefault();

    const target = e.target as typeof e.target & {
      date: { value: string };
      weight: { value: number };
      bodyFatRatio: { value: number };
    };

    const date = target.date.value;
    const weight = target.weight.value;
    const bodyFatRatio = target.bodyFatRatio.value;
    console.log('submit values', {
      date,
      weight,
      bodyFatRatio,
    });
  };
  return (
    <>
      <Head>
        <title>Cleric - Record weight</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <form action="" onSubmit={handleSubmit}>
          <div>
            <label>
              Date: <input type="date" name="date" defaultValue={now} />
            </label>
          </div>
          <div>
            <label>
              Weight: <input type="number" name="weight" step=".1" />
            </label>
          </div>
          <div>
            <label>
              Body fat ratio:{' '}
              <input type="number" name="bodyFatRatio" step=".1" />
            </label>
          </div>
          <button>Record</button>
        </form>
      </main>
    </>
  );
}
